### ISSUE TITLE
Weekly scrum - [3/13/2020] 🍺 ☣️ 

### ISSUE THREAD

**Issue by dipshit** [vikrambombhi/SimpleSurvey#38]
Last week I worked on:
 * The class hierarchy: #27 

this week I will work on:
 * UML #40 
 * Allowing multiple answers/responses to questions #37

I am blocked by reviews on #37

**Comment by JackyChiu** [comment]
This scrum I working on:
- #34 closing a survey
- fixing test structure for better json testing
- fixing minor bugs

**Comment by ismail-syed** [comment]
Last week: 
* Setup app navigation and pages https://github.com/vikrambombhi/SimpleSurvey/pull/51
* Create survey form  - https://github.com/vikrambombhi/SimpleSurvey/pull/48

This week: 
* List all the questions in the survey on the card - https://github.com/vikrambombhi/SimpleSurvey/issues/52
* Allow users to answer questions from a survey

**Comment by bkzhang** [comment]
Last  scrum:

- added travis conf #2 
- added survey and text question tests #4 

This scrum:

- drew er diagrams #62 
- added the controller functionality so that when a new survey is created in `/api/new`, the entire survey object is passed as the body including its questions and answers so that the creation of the survey and question happens at the same time

**Comment by vikrambombhi** [comment]
- added the ability to preview questions in while viewing surveys
![image](https://user-images.githubusercontent.com/14275982/77194452-6340ba80-6ab6-11ea-869f-ece70323b415.png)

- added page for submitting survey answers. This page dynamically creates a form using the survey object.
![image](https://user-images.githubusercontent.com/14275982/77194552-9125ff00-6ab6-11ea-98da-7f815ba91a16.png)
