### ISSUE TITLE
Weekly scrum - [3/20/2020] 

### ISSUE THREAD

**Issue by ismail-syed** [vikrambombhi/SimpleSurvey#67]
Last week: 
- Moved create survey from modal to a page - https://github.com/vikrambombhi/SimpleSurvey/pull/58 
- Fixed form submit - https://github.com/vikrambombhi/SimpleSurvey/pull/55

This week: 
- Polish up UI in places that need love

**Comment by bkzhang** [comment]
Last week:

- started adding the ability to add questions through question controllers that got refactored in same issue below (#6) 

This week:

- drew er diagrams #41 
- added the controller functionality so that when a new survey is created in `/api/new`, the entire survey object is passed as the body including its questions and answers #6

**Comment by dipshit** [comment]
Last week I
* Updated the form for adding questions #63 
* Reviewed a bunch of PRs

Next week I will clean up the form:
 * #64
